unit untCommands;

interface

const
  CMD_ONLINE = 0;
  CMD_SHELLCODE_QUESTION = 1;
  CMD_SHELLCODE_NEW = 2;
  CMD_SHELLCODE_ADD = 3;
  CMD_SHELLCODE_CALL = 4;
  CMD_DRIVE_LIST = 5;
  CMD_LIST_DIR_START = 6;
  CMD_LIST_DIR_WRITE = 7;
  CMD_LIST_DIR_FINISHED = 8;
  CMD_LIST_DIR_ERROR = 9;
  CMD_FILE_DELETE_OK = 10;
  CMD_FILE_DELETE_FAIL = 11;
  CMD_FILE_EXECUTE_OK = 12;
  CMD_FILE_EXECUTE_FAIL = 13;

  CMD_PROCESS_LIST_START = 20;
  CMD_PROCESS_LIST_END = 21;
  CMD_PROCESS_LISTWRITE = 22;

implementation

end.
