unit untCommands;

interface

const
  CMD_ONLINE = 0;
  CMD_SHELLCODE_QUESTION = 1;
  CMD_SHELLCODE_NEW = 2;
  CMD_SHELLCODE_ADD = 3;
  CMD_SHELLCODE_CALL = 4;
  CMD_DRIVE_LIST = 5;
  CMD_LIST_DIR_START = 6;
  CMD_LIST_DIR_WRITE = 7;
  CMD_LIST_DIR_FINISHED = 8;
  CMD_LIST_DIR_ERROR = 9;

implementation

end.
